---
- hosts: 127.0.0.1
  become: True
  # Ansible User
  become_user: some_user
  gather_facts: no
  vars:
    ansible_python_interpreter: /bin/python3
    # Variables -----
    port: 8001
    port_devel: 8002
    secret_key: "your_secret_key_here"
    db_user: "your_db_user_here"
    db_name: "your_db_name_here"
    db_name_devel: "your_db_name_devel_here"
    db_pass: "your_db_password_here"
    app_name: "your_app_name_here"
    app_name_devel: "your_app_name_devel_here"
    proj_name: "{{ app_name }}"
    app_user: "your_app_user_here"
    server_name: "your_domain_here.com"
    server_name_www: "www.your_domain_here.com"
    server_name_devel: "devel.your_domain_here.com"
    domain: your_domain_here.com
    domain_devel: devel.your_domain_here.com
    your_email: "youremail@domain.com"
    git_link: https://github.com/your_git_user/your_app.git
    #--- End Variables
    proj_dir: "/home/some_user/apps/{{ app_name }}/{{ proj_name }}"
    proj_dir_devel: "/home/some_user/apps/devel/{{ app_name }}/{{ proj_name }}"
    app_dir: "/home/some_user/apps/{{ app_name }}/{{ proj_name }}/{{ app_name }}"
    app_dir_devel: "/home/some_user/apps/devel/{{ app_name }}/{{ proj_name }}/{{ app_name }}"
    venv_dir: "/home/some_user/apps/{{ app_name }}"
    venv_dir_devel: "/home/some_user/apps/devel/{{ app_name }}"
    venv_name: "{{ app_name }}"
    venv_name_devel: "{{ app_name }}-devel"
    etc_dir: "/etc/gunicorn_deployment"
    enabled_sites: "/etc/nginx/sites-enabled/"
  roles:
  - role: "deploy/django_app/postgres"
    tags: ['postgres']
  - role: 'deploy/django_app/app'
    tags: ['app']
  - role: 'deploy/django_app/gunicorn'
    tags: ['gunicorn']
  - role: 'deploy/django_app/nginx'
    tags: ['nginx']
  - role: 'deploy/django_app/certbot'
    tags: ['certbot']
  - role: 'deploy/django_app/gitpull'
    tags: ['git_pull']
